site_name: MVC::Keayl
site_url: https://gdonald.github.io/MVC-Keayl/
repo_url: https://github.com/gdonald/MVC-Keayl
nav:
  - Home: index.md
  - Request: request.md
  - Response: response.md
  - Middleware: middleware.md
  - Server adapters: adapters.md
  - Routing: routing.md
  - Controllers: controllers.md
  - Views: views.md
  - View helpers: helpers.md
  - Cookies: cookies.md
  - Sessions: sessions.md
theme:
  name: 'material'
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
